(define (proc a b c)
    (cond ((and (<= a b)
               (<= a c))
            (+ b c))
          ((and (<= b a)
                (<= b c))
            (+ a c))
          ((and (<= c a)
                (<= c b))
            (+ a b))))
(proc 3 5 1)
