(define (add-streams s1 s2)
  (stream-map + s1 s2))
(define (stream-map proc s)
  (if (stream-null? s)
      the-empty-stream
      (cons-stream (proc (stream-car s))
                   (stream-map proc (stream-cdr s)))))
(define s (cons-stream 1 (add-streams s s)))
(define x 10)
(delay x)
